version: "3.3"

services:
  detector:
    build:
      context: .
      dockerfile: docker/detector.Dockerfile
    container_name: detector
    environment:
      TOKEN: ${TOKEN}
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 4096M
        reservations:
          cpus: "0.25"
          memory: 1024M
    volumes:
      - "./detector:/app/detector"
    ports:
      - "9090:9090"
    entrypoint: uvicorn detector.main:app --host 0.0.0.0 --port 9090 --reload
  # parser:
  #   build:
  #     context: .
  #     dockerfile: docker/parser.Dockerfile
  #   container_name: parser
  #   environment:
  #     DETECTOR: detector
  #     TOKEN: ${TOKEN}
  #   restart: on-failure
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.30"
  #         memory: 2048M
  #       reservations:
  #         cpus: "0.25"
  #         memory: 1024M
  #   volumes:
  #     - "./parser:/app/parser"
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - detector
  #   entrypoint: uvicorn parser.main:app --host 0.0.0.0 --port 8080 --reload
  # bot:
  #   build:
  #     context: .
  #     dockerfile: docker/bot.Dockerfile
  #   container_name: parser_bot
  #   environment:
  #     PARSER: parser
  #     TOKEN: ${TOKEN}
  #   volumes:
  #     - "./bot:/app/bot"
    # depends_on:
      # - parser
    # entrypoint: poetry run python3 -m bot

  # lab:
  #   build:
  #     context: .
  #     dockerfile: docker/lab.Dockerfile
  #   container_name: parser_lab
  #   restart: on-failure
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.50"
  #         memory: 2048M
  #       reservations:
  #         cpus: "0.25"
  #         memory: 1024M
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./lab:/app
  #   entrypoint: jupyter lab --ip=0.0.0.0 --port=8081 --no-browser --allow-root
