version: "3.3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
  detector:
    image: detector:pymongo-v1.0
    container_name: detector
    environment:
      TOKEN: ${TOKEN}
      MONGO: mongodb://root:secret@mongodb:27017
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "1.25"
          memory: 4096M
        reservations:
          cpus: "0.25"
          memory: 1024M
    volumes:
      - "./detector:/app/detector"
    ports:
      - "9090:9090"
    entrypoint: uvicorn detector.main:app --host 0.0.0.0 --port 9090 --reload
  bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    container_name: parser_bot
    environment:
      PARSER: parser
      TOKEN: ${TOKEN}
      MONGO: mongodb://root:secret@mongodb:27017
      TF_DETECTOR: tf_detector
    volumes:
      - "./bot:/app/bot"
      - "./data:/tmp/data"
    entrypoint: poetry run python3 -m bot